server:
  host: "127.0.0.1"
  port: 50051
  timeout:
    server: 30
    read: 15
    write: 19
    idle: 5
db_conf:
  user: "admin",
  password: "123",
  database: "go_api",
  host: "localhost",
  port: 3306,